# Generated by Django 2.2.3 on 2020-06-03 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dbconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=16)),
                ('port', models.CharField(max_length=5)),
                ('env', models.CharField(choices=[('prd', '生产环境'), ('test', '测试环境')], max_length=20)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inceptsql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('commiter', models.CharField(blank=True, max_length=20, null=True)),
                ('sql_content', models.TextField()),
                ('env', models.CharField(choices=[('prd', '生产环境'), ('test', '测试环境')], max_length=20)),
                ('treater', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(-3, '已回滚'), (-2, '已暂停'), (-1, '待执行'), (0, '已执行'), (1, '已放弃'), (2, '执行失败')], default=-1)),
                ('execute_errors', models.TextField(blank=True, default='', null=True)),
                ('exe_affected_rows', models.CharField(blank=True, max_length=10, null=True)),
                ('roll_affected_rows', models.CharField(blank=True, max_length=10, null=True)),
                ('rollback_opid', models.TextField(blank=True, null=True)),
                ('rollback_db', models.CharField(blank=True, max_length=100, null=True)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlmng.Dbconf')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
