# Generated by Django 2.2.14 on 2020-09-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='DbConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=64)),
                ('port', models.CharField(max_length=5)),
                ('env', models.CharField(choices=[('prd', '生产环境'), ('test', '测试环境')], max_length=8)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sqlmng.Cluster')),
                ('related_user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('name', 'host', 'env', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='InceptionConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('host', models.CharField(blank=True, default='127.0.0.1', max_length=64, null=True)),
                ('port', models.CharField(blank=True, default=6669, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InceptionVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('param', models.CharField(blank=True, max_length=64, null=True)),
                ('default', models.CharField(blank=True, max_length=16, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InceptionWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('is_manual_review', models.BooleanField(default=False, verbose_name='有流程')),
                ('commiter', models.CharField(blank=True, max_length=64, null=True)),
                ('sql_content', models.TextField()),
                ('env', models.CharField(choices=[('prd', '生产环境'), ('test', '测试环境')], max_length=8)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('treater', models.CharField(max_length=64)),
                ('status', models.IntegerField(choices=[(-3, '回滚成功'), (-2, '已暂停'), (-1, '待执行'), (0, '执行成功'), (1, '已放弃'), (2, '任务异常'), (3, '审批通过'), (4, '审批驳回'), (5, '已定时'), (6, '执行中'), (7, '回滚中')], default=-1)),
                ('execute_errors', models.TextField(blank=True, default='', null=True)),
                ('execute_time', models.CharField(blank=True, max_length=32, null=True)),
                ('rollback_time', models.CharField(blank=True, max_length=32, null=True)),
                ('affected_rows', models.CharField(blank=True, max_length=16, null=True)),
                ('roll_affected_rows', models.CharField(blank=True, max_length=10, null=True)),
                ('rollback_opid', models.TextField(blank=True, null=True)),
                ('rollback_db', models.CharField(blank=True, max_length=128, null=True)),
                ('rollback_able', models.BooleanField(default=False, verbose_name='可回滚')),
                ('cron_time', models.CharField(blank=True, max_length=64, null=True)),
                ('handle_result', models.TextField(blank=True, default='', null=True, verbose_name='处理详情')),
                ('handle_result_check', models.TextField(blank=True, default='', null=True, verbose_name='审核详情')),
                ('handle_result_execute', models.TextField(blank=True, default='', null=True, verbose_name='执行详情')),
                ('handle_result_rollback', models.TextField(blank=True, default='', null=True, verbose_name='回滚详情')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlmng.DbConf')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='MailActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('value', models.BooleanField(default=True, verbose_name='是否发送')),
                ('desc_cn', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SqlSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('forbidden_words', models.TextField(blank=True, default='', null=True)),
                ('sql_count_limit', models.IntegerField(blank=True, default=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('is_manual_review', models.BooleanField(default=False, verbose_name='有流程')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlmng.InceptionWorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核驳回'), (3, '放弃')], default=0)),
                ('env', models.CharField(blank=True, choices=[('prd', '生产环境'), ('test', '测试环境')], max_length=8, null=True)),
                ('db_host', models.CharField(blank=True, max_length=64, null=True)),
                ('db_port', models.CharField(blank=True, max_length=5, null=True)),
                ('db_list', models.TextField(blank=True, default='', null=True)),
                ('commiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commiter', to=settings.AUTH_USER_MODEL)),
                ('db_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sqlmng.Cluster')),
                ('treater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
