# Generated by Django 2.2.3 on 2020-06-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmng', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inceptsql',
            options={'verbose_name': 'sql执行', 'verbose_name_plural': 'sql执行'},
        ),
    ]
