# Generated by Django 2.2.14 on 2020-09-19 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='机柜名称', max_length=50, verbose_name='机柜名称')),
                ('power_supply', models.IntegerField(help_text='电源功率', verbose_name='电源功率')),
            ],
            options={
                'verbose_name': '机柜信息',
                'verbose_name_plural': '机柜信息',
                'db_table': 'resources_cabinet',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(help_text='idc字母简称', max_length=10, unique=True, verbose_name='idc字母简称')),
                ('name', models.CharField(help_text='idc名称', max_length=30, verbose_name='idc名称')),
                ('address', models.CharField(blank=True, help_text='idc具体地址', max_length=255, null=True, verbose_name='idc具体地址')),
                ('tel', models.CharField(blank=True, help_text='客服电话', max_length=15, null=True, verbose_name='客服电话')),
                ('mail', models.EmailField(blank=True, help_text='联系人邮箱', max_length=255, null=True, verbose_name='联系人邮箱')),
                ('remark', models.CharField(blank=True, help_text='备注说明', max_length=255, null=True, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '机房信息',
                'verbose_name_plural': '机房信息',
                'db_table': 'resources_idc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(db_index=True, help_text='厂商名称', max_length=32, verbose_name='厂商名称')),
                ('tel', models.CharField(help_text='联系电话', max_length=20, null=True, verbose_name='联系电话')),
                ('mail', models.EmailField(blank=True, help_text='联系邮箱', max_length=254, null=True, verbose_name='email')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=300, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '厂商信息',
                'verbose_name_plural': '厂商信息',
                'db_table': 'resources_manufacturer',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='业务线名称', max_length=32, verbose_name='业务线名称')),
                ('pid', models.IntegerField(db_index=True, help_text='上级业务线id', verbose_name='上级业务线id')),
                ('module_letter', models.CharField(help_text='业务线字母简称', max_length=32, verbose_name='业务线字母简称')),
                ('dev_interface', models.ManyToManyField(help_text='开发接口人', related_name='dev_interface', to=settings.AUTH_USER_MODEL, verbose_name='开发接口人')),
                ('op_interface', models.ManyToManyField(help_text='运维接口人', related_name='op_interface', to=settings.AUTH_USER_MODEL, verbose_name='运维接口人')),
            ],
            options={
                'verbose_name': '业务线',
                'verbose_name_plural': '业务线',
                'db_table': 'resources_product',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='型号名称', max_length=32, verbose_name='型号名称')),
                ('vendor', models.ForeignKey(help_text='所属制造商', on_delete=django.db.models.deletion.CASCADE, to='resources.Manufacturer', verbose_name='所属制造商')),
            ],
            options={
                'verbose_name': '型号信息',
                'verbose_name_plural': '型号信息',
                'db_table': 'resources_productmodel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_data', models.DateField(help_text='制造日期', null=True, verbose_name='制造日期')),
                ('cabinet_position', models.CharField(help_text='机柜内位置', max_length=32, null=True, verbose_name='机柜内位置')),
                ('warranty_time', models.DateField(help_text='保修时间', null=True, verbose_name='保修时间')),
                ('purchasing_time', models.DateField(help_text='采购时间', null=True, verbose_name='采购时间')),
                ('power_supply', models.IntegerField(help_text='电源功率', null=True, verbose_name='电源功率')),
                ('os', models.CharField(default=None, help_text='操作系统', max_length=100, verbose_name='操作系统')),
                ('hostname', models.CharField(db_index=True, default=None, help_text='主机名', max_length=50, verbose_name='主机名')),
                ('manage_ip', models.CharField(db_index=True, default=None, help_text='管理IP', max_length=32, verbose_name='管理IP')),
                ('server_cpu', models.CharField(default=None, help_text='CPU信息', max_length=250, verbose_name='CPU信息')),
                ('disk', models.CharField(help_text='硬盘信息', max_length=300, null=True, verbose_name='硬盘信息')),
                ('server_mem', models.CharField(default=None, help_text='内存信息', max_length=100, verbose_name='内存信息')),
                ('status', models.CharField(db_index=True, help_text='服务器状态', max_length=32, null=True, verbose_name='服务器状态')),
                ('remark', models.TextField(help_text='备注', null=True, verbose_name='备注')),
                ('last_check', models.DateTimeField(auto_now=True, help_text='上次检测时间', verbose_name='上次检测时间')),
                ('uuid', models.CharField(db_index=True, help_text='UUID', max_length=100, null=True, unique=True, verbose_name='UUID')),
                ('sn', models.CharField(db_index=True, help_text='SN', max_length=40, null=True, verbose_name='SN')),
                ('rmt_card_ip', models.CharField(help_text='远程管理卡IP', max_length=15, null=True, verbose_name='远程管理卡IP')),
                ('server_type', models.IntegerField(db_index=True, default=0, help_text='机器类型', verbose_name='机器类型')),
                ('cabinet', models.ForeignKey(help_text='所在机柜', null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Cabinet', verbose_name='所在机柜')),
                ('idc', models.ForeignKey(help_text='所在机房', null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Idc', verbose_name='所在机房')),
                ('manufacturer', models.ForeignKey(help_text='制造商', null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Manufacturer', verbose_name='制造商')),
                ('model_name', models.ForeignKey(default=None, help_text='服务器型号', on_delete=django.db.models.deletion.CASCADE, to='resources.ProductModel', verbose_name='服务器型号')),
                ('server_purpose', models.ForeignKey(help_text='二级产品线', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_purpose', to='resources.Product', verbose_name='二级产品线')),
                ('service', models.ForeignKey(help_text='一级业务线', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='resources.Product', verbose_name='一级业务线')),
            ],
            options={
                'verbose_name': '机器信息',
                'verbose_name_plural': '机器信息',
                'db_table': 'resources_server',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网卡设备名')),
                ('mac', models.CharField(max_length=32, verbose_name='网卡mac地址')),
                ('remark', models.CharField(max_length=300, null=True, verbose_name='备注')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Server', verbose_name='所在服务器')),
            ],
            options={
                'verbose_name': '网卡信息',
                'verbose_name_plural': '网卡信息',
                'db_table': 'resources_networkdevice',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(db_index=True, max_length=20, verbose_name='ip地址')),
                ('netmask', models.CharField(max_length=20, verbose_name='子网掩码')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.NetworkDevice', verbose_name='网卡')),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IP',
                'db_table': 'resources_ip',
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(help_text='所在机房', on_delete=django.db.models.deletion.CASCADE, to='resources.Idc', verbose_name='所在机房'),
        ),
    ]
