# Generated by Django 2.2.3 on 2020-06-06 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='名称')),
                ('parent', models.IntegerField(verbose_name='父亲级别')),
                ('level', models.IntegerField(verbose_name='层级')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务树',
                'verbose_name_plural': '服务树',
                'db_table': 'service_tree',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='service名称', max_length=32, verbose_name='节点名称')),
                ('pid', models.IntegerField(db_index=True, help_text='pid', verbose_name='节点pid')),
                ('path', models.CharField(db_index=True, help_text='node中文path', max_length=32, verbose_name='节点中文path')),
                ('rd', models.CharField(blank=True, help_text='业务负责人', max_length=255, null=True, verbose_name='业务负责人')),
                ('op', models.CharField(blank=True, help_text='运维负责人', max_length=255, null=True, verbose_name='运维负责人')),
                ('groups', models.ManyToManyField(help_text='用户组关联节点', related_name='node_group', to='rbac.Organization', verbose_name='用户组关联节点')),
            ],
            options={
                'db_table': 'servicetree_node',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BindCMDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_tree', models.IntegerField(verbose_name='服务树ID')),
                ('classification', models.IntegerField(verbose_name='分类ID')),
                ('table', models.IntegerField(verbose_name='表ID')),
                ('data', models.IntegerField(verbose_name='数据ID')),
            ],
            options={
                'verbose_name': '服务树绑定CMDB',
                'verbose_name_plural': '服务树绑定CMDB',
                'db_table': 'service_tree_cmdb',
                'index_together': {('service_tree', 'classification', 'table')},
            },
        ),
    ]
