# Generated by Django 2.2.14 on 2020-09-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=128, verbose_name='任务名称')),
                ('uuid', models.CharField(max_length=128, verbose_name='任务执行唯一ID')),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('status', models.CharField(max_length=128, verbose_name='任务状态')),
                ('content', models.TextField(blank=True, null=True, verbose_name='任务状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '执行历史',
                'verbose_name_plural': '执行历史',
                'db_table': 'task_history',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='任务名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='任务内容')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='任务描述')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
                'db_table': 'task_list',
            },
        ),
    ]
