# Generated by Django 2.2 on 2020-04-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128, verbose_name='任务ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='任务名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='任务内容')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='任务描述')),
                ('state', models.CharField(default='WAITING', max_length=45, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
                'db_table': 'task_list',
            },
        ),
        migrations.CreateModel(
            name='TaskToAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128, verbose_name='任务ID')),
                ('agent_id', models.CharField(max_length=128, verbose_name='agent id')),
                ('state', models.CharField(default='WAITING', max_length=45, verbose_name='任务状态')),
                ('output', models.TextField(blank=True, null=True, verbose_name='返回结果')),
            ],
            options={
                'verbose_name': '任务与agent的关联',
                'verbose_name_plural': '任务与agent的关联',
                'db_table': 'task_agent',
            },
        ),
        migrations.CreateModel(
            name='ToolGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='分组名称')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='分组描述')),
            ],
            options={
                'verbose_name': '工具分组',
                'verbose_name_plural': '工具分组',
                'db_table': 'task_tool_groups',
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='工具名称')),
                ('tid', models.CharField(max_length=128, verbose_name='工具唯一ID')),
                ('types', models.CharField(max_length=45, verbose_name='工具类型')),
                ('entry_name', models.CharField(max_length=128, verbose_name='入口文件名称')),
                ('desc', models.CharField(max_length=128, verbose_name='描述')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.ToolGroups', verbose_name='工具分组')),
            ],
            options={
                'verbose_name': '工具列表',
                'verbose_name_plural': '工具列表',
                'db_table': 'task_tools',
            },
        ),
    ]
