# Generated by Django 2.2 on 2020-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskToAgent',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='task_id',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.DeleteModel(
            name='ToolGroups',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
