# Generated by Django 2.2.14 on 2020-07-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicefile',
            options={'verbose_name': '设备文件', 'verbose_name_plural': '设备文件'},
        ),
    ]
