# Generated by Django 2.2.14 on 2020-09-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20200716_1631'),
        ('cmdb', '0002_auto_20200919_1232'),
    ]

    operations = [
    ]
