# Generated by Django 2.2.1 on 2020-05-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='groups',
            field=models.ManyToManyField(help_text='用户组关联权限', related_name='pms_org', to='orgs.Organization', verbose_name='用户组关联权限'),
        ),
    ]
