# Generated by Django 2.2.14 on 2020-07-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/vue.gif', null=True, upload_to='static/%Y/%m'),
        ),
    ]
