# Generated by Django 2.2.14 on 2020-09-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200716_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_rsa_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_rsa_pub',
            field=models.TextField(null=True),
        ),
    ]
