# Generated by Django 2.2.14 on 2020-09-19 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('rbac', '0002_auto_20200716_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiHttpMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('method', models.CharField(max_length=32, unique=True, verbose_name='HTTP Method')),
            ],
            options={
                'verbose_name': 'API Method',
                'verbose_name_plural': 'API Method',
                'db_table': 'api_http_method',
            },
        ),
        migrations.CreateModel(
            name='ApiPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='API名称')),
                ('uri', models.CharField(max_length=100, verbose_name='HTTP URI')),
                ('api_http_methods', models.ManyToManyField(blank=True, related_name='api_http_methods', to='rbac.ApiHttpMethod', verbose_name='API权限')),
            ],
            options={
                'verbose_name': 'API权限',
                'verbose_name_plural': 'API权限',
                'db_table': 'api_permission',
            },
        ),
        migrations.CreateModel(
            name='PerAppName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(help_text='APPkey', max_length=64, unique=True, verbose_name='APPkey')),
                ('app_name', models.CharField(help_text='APP名称', max_length=32, verbose_name='APP名称')),
                ('app_desc', models.CharField(help_text='APP应用描述', max_length=32, verbose_name='APP应用描述')),
            ],
            options={
                'db_table': 'pms_app',
            },
        ),
        migrations.CreateModel(
            name='PmsPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='权限简称', max_length=32, verbose_name='权限简称')),
                ('desc', models.CharField(help_text='权限描述信息', max_length=32, verbose_name='权限描述信息')),
                ('app', models.CharField(help_text='APP名称', max_length=32, verbose_name='APP名称')),
                ('groups', models.ManyToManyField(help_text='用户组关联权限', related_name='pms_group', to='auth.Group', verbose_name='用户组关联权限')),
            ],
            options={
                'db_table': 'pms_permission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(db_index=True, help_text='service名称', max_length=32, verbose_name='节点名称')),
                ('pid', models.IntegerField(db_index=True, help_text='pid', verbose_name='节点pid')),
                ('path_node', models.CharField(db_index=True, help_text='node中文path', max_length=32, verbose_name='节点中文path')),
                ('groups', models.ManyToManyField(help_text='用户组关联节点', related_name='node_group', to='auth.Group', verbose_name='用户组关联节点')),
            ],
            options={
                'db_table': 'pms_node',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApiPermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='组名')),
                ('api_permissions', models.ManyToManyField(blank=True, related_name='api_permissions', to='rbac.ApiPermission', verbose_name='API权限')),
                ('users', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API权限组',
                'verbose_name_plural': 'API权限组',
                'db_table': 'api_permission_group',
            },
        ),
    ]
