# Generated by Django 2.2.14 on 2020-07-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='status1',
            field=models.IntegerField(choices=[(0, '申请'), (1, '已审核'), (2, '灰度'), (3, '上线'), (4, '取消上线')], default=0, verbose_name='上线状态'),
        ),
    ]
