# Generated by Django 2.2.14 on 2020-09-25 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_ids', models.TextField(blank=True, null=True, verbose_name='主机列表')),
                ('command', models.TextField(blank=True, null=True, verbose_name='salt命令')),
                ('type', models.CharField(choices=[(0, 'shell'), (1, 'state')], default=0, max_length=2, verbose_name='操作类型')),
                ('executor', models.CharField(max_length=32, verbose_name='执行人')),
                ('execute_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'salt操作',
                'db_table': 'salt_cmd_history',
            },
        ),
        migrations.CreateModel(
            name='MinionsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_id', models.CharField(blank=True, max_length=128, null=True)),
                ('minion_status', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'salt_minions_status',
            },
        ),
        migrations.CreateModel(
            name='SaltAcl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='ACL名称')),
                ('description', models.CharField(max_length=128, verbose_name='描述')),
                ('deny', models.CharField(max_length=64, verbose_name='拒绝权限')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': 'salt权限控制',
                'db_table': 'salt_acl',
            },
        ),
        migrations.CreateModel(
            name='SaltArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='cmd.run模块参数名称')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': 'salt参数名称',
                'db_table': 'salt_arg',
            },
        ),
        migrations.CreateModel(
            name='SaltMdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='模块名称')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': 'salt模块名称',
                'db_table': 'salt_mdl',
            },
        ),
        migrations.CreateModel(
            name='SaltSls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='状态文件名称')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': 'salt状态文件',
                'db_table': 'salt_sls',
            },
        ),
    ]
