# Generated by Django 2.2.14 on 2020-07-16 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_ids', models.TextField(blank=True, null=True, verbose_name='主机列表')),
                ('command', models.TextField(blank=True, null=True, verbose_name='salt命令')),
                ('type', models.CharField(choices=[(0, 'shell'), (1, 'state')], default=0, max_length=2, verbose_name='操作类型')),
                ('executor', models.CharField(max_length=32, verbose_name='执行人')),
                ('execute_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'salt操作',
                'db_table': 'salt_cmd_history',
            },
        ),
        migrations.CreateModel(
            name='SaltArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='cmd.run模块参数名称')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': 'salt参数名称',
                'db_table': 'salt_arg',
            },
        ),
    ]
