# Generated by Django 2.2 on 2020-03-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_auto_20200324_1315'),
        ('permission', '0003_auto_20200323_2243'),
    ]

    operations = [
    ]
